title: "Angel Dollface"
pfpUrl: "https://avatars.githubusercontent.com/u/112771657?v=4"
description: "A doll's blog and personal website."
prod_url: ""
dev_url: ""
keywords: "blog lifestyle-blog doll blogger-doll"
closingText: "Close"
menuText: "explore"
updateFreq: "weekly"
navElem: "nav"
tlDomain: "https://angeldollface.boo"
copyFiles: "true=>CNAME|assets"
hasLoopContent: "false"
readMeText: "Read"
analyticsId: "G-902CP5DY95"
build_log: "true"
lastUpdatedText: "Last update:"
landingHeading: "Hi! I'm Angel Dollface!"
landingPara: "I'm a designer, developer, DJ, artist and you have reached my official website!"
mastodonLink: "https://corteximplant.com/@angeldollface666"
icon_five_seven: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-57x57.png"
icon_six_zero: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-60x60.png"
icon_seven_two: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-72x72.png"
icon_seven_six: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-76x76.png"
icon_one_one_four: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-114x114.png"
icon_one_two_zero: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-120x120.png"
icon_one_four_four: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-144x144.png"
icon_one_five_two: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-152x152.png"
icon_one_eight_zero: "https://angeldollface.boo/doll-cdn/images/site/favicons/apple-icon-180x180.png"
icon_one_nine_two: "https://angeldollface.boo/doll-cdn/images/site/favicons/android-icon-192x192.png"
icon_three_two: "https://angeldollface.boo/doll-cdn/images/site/favicons/favicon-32x32.png"
icon_nine_six: "https://angeldollface.boo/doll-cdn/images/site/favicons/favicon-96x96.png"
icon_one_six: "https://angeldollface.boo/doll-cdn/images/site/favicons/favicon-16x16.png"
icon_ms_one_four_four: "https://angeldollface.boo/doll-cdn/images/site/favicons/ms-icon-144x144.png"
