title: "Angel Dollface"
pfp: "https://avatars.githubusercontent.com/u/112771657?v=4"
description: "A doll's blog and personal website."
prod_url: ""
dev_url: ""
keywords: "blog lifestyle-blog doll blogger-doll"
closingText: "Close"
menuText: "Menu"
menuButtonElem: "menu"
updateFreq: "weekly"
navElem: "nav"
tlDomain: "https://angeldollface.boo"
copyFiles: "true=>CNAME|assets"
motto: "Everyone's favorite doll!"
hasLoopContent: "false"
analyticsId: "G-902CP5DY95"
build_log: "true"
easterEggButtonText: "DOLL"
slogan: "Everyone's favourite doll!"
mastodonLink: "https://mastodon.social/@angeldollface666"